server:
  port: 9996

spring:
  application:
    name: API-BULLETS
  cloud:
    nacos:
      server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity

netty:
  websocket:
    # Websocket????
    port: 9123
    # ?????
    ip: 0.0.0.0
    # ???????
    max-frame-size: 10240
    # URI??
    path: /channel

logging:
  level:
    com:
      baizhi:
        dao: debug


