server:
  port: 9992

spring:
  application:
    name: API-USERS
  cloud:
    nacos:
      server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity

logging:
  level:
    com:
      baizhi:
        dao: debug
#qiniu:
#  key:
#    access: JHp93XBDkXcatVjjEpOpKLsfZSMVWobZtSL1AAzk
#    secret: Npfi1hfmKHP9uX9Blxgu1o6wmbk2Sc0QYZ1924tw
#  bucket:
#    header:
#      name: ustcheader
#      url: http://rjgrxz94l.bkt.clouddn.com
#    share:
#      name: ustcshare
#      url: http://rjgrxz94l.bkt.clouddn.com

#设置openfeign调用超时
feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000